joaotavora/yasnippet

- doc/snippet-development.org
Added more detail about how yas-new-snippet behaves, particularly how it guesses a directory to save in. I was a bit confused by this when I first tried it out, so I attempted to clarify the description here.
> Small doc change: Clarify what happens with yas-new-snippet.

- yasnippet.el
The code removed is dead code originating from the days when `ruby-mode`
wasn't included in Emacs yet.
> Implement suggestion as seen in issue #566

- doc/snippet-organization.org
- yasnippet.el
It is hoped that this will add clarity.
* yasnippet.el, doc/snippet-organization.org (documentation):
Replaced 'shadow' with 'override' globally.
> Replaced 'shadow' with 'override' throughout documentation

- doc/yas-doc-helper.el
On emacs24, Debian, HTML doc generation finishes with this error.
> Fix "invalid function: quote"

- doc/snippet-expansion.org
- doc/snippet-menu.org
- yasnippet-tests.el
- yasnippet.el
https://github.com/capitaomorte/yasnippet/issues/595#issuecomment-126965778:
> yas--all-templates is affected by yas-choose-tables-first and yas-choose-keys-first which should be let-bound to nil so the user isn't prompted like in interactive yas-expand. It's also affected by yas-buffer-local-condition, which should probably be turned off, but here I'm not so sure.
I made it honour `yas-buffer-local-condition` because it seems plausibly useful and the caller can always let-bind it themselves.
> My idea of the mode argument is that, if it is passed, then only the tables for that mode (and perhaps its parents) are used, but yas--extra-modes being buffer-local, cannot be used, so let-bind it to nil. If mode is not used, then use yas--get-snippet-tables as usual.
I made …
> Add yas-lookup-snippet

- doc/snippet-organization.org
Specifically, fill in the section about `.yas-compiled-snippet.el`, which was previously labelled as TODO.
I took the liberty to add a caveat about #597.
> Add documentation for snippet compilation

- yasnippet-tests.el
- yasnippet.el
Removes [choice between `apply #'append` and `reduce #'append`][1] by removing need for either.
replace/ close #620.
[1]: https://github.com/capitaomorte/yasnippet/pull/620#commitcomment-13697599
> find parents for extra-modes too (v2)

- yasnippet.el
```
It is not a very pleasant method when there are many values, and
`yas-completing-prompt' will usually do a better job, in addition to
respecting customizations to `completing-read-function'.
`yas-dropdown-prompt' remains in first place, since it only takes effect
if the `dropdown' library is loaded, which likely indicates a preference
for it.
* yasnippet.el (yas-prompt-functions): Remove yas-x-prompt from default value.
```
Fixes #655. I intend to merge this *before* the release.
> Don't use yas-x-prompt by default

- yasnippet.el
```
* yasnippet.el (yas-new-snippet-default): Remove
"require-final-newline: nil", it's redundant since `snippet-mode' already
sets that.  Also remove the direct-keybinding, since it's hardly ever
used, and often the literal "# binding: direct-keybinding" ends up in
actual snippets.
```
One last(?) thing before release.
> Reduce `yas-new-snippet-default'

- yasnippet.el
```
* yasnippet.el (yas--font-lock-keywords): ignore-errors from
emacs-lisp-mode call, in case user's hooks cause problems (e.g. enabling
`yas-minor-mode' before we finish loading).
```
fix #673, replace/ close #674.
> Avoid potential problems with user's hooks

- yasnippet.el
Fixes #677, I think also fixes #666.
```
cc-mode modifies text properties in the buffer do cache parsing results,
therefore it's important that yasnippet not kill yasnippets when parsing
is triggered by function that only wants to parse the
buffer (e.g. which-function-mode).
* yasnippet.el (yas--buffer-pre-modification): New variable.
(yas--on-protection-overlay-modification): Save buffer text (without
properties) on the before change call, and compare on the after change
call.
```
> Don't kill snippets for text property modification

- yasnippet.el
Fixes #662.
```
In [1] we started deciding clearing based on a command's
delete-selection property, but it turns out that some commands perform
insertion, and optionally use the region's contents.  So these commands
should have a nil delete-selection property, but they still ought to
clear a snippet field when used.
To achieve this, we now check if the command has inserted text in the
post-change hook of the field overlay.
* yasnippet.el (yas--skip-and-clear): Add optional FROM paramter.  Only
clear non-empty fields.
(yas--skip-and-clear-field-p): Check the pre-change point and length
instead of current command delete-selection property.
(yas--on-field-overlay-modification): Perform field clearing on the
post-change call.
[1]: acf2cdd "Decide field clearing commands based on delsel"
```
> Decide field clearing based on command's effect

- yasnippet-tests.el
- yasnippet.el
See http://emacs.stackexchange.com/questions/19206/fill-column-conflicts-with-yasnippet-examples-in-gif
This is a tentative fix. I've found that there is some strange interaction with `yas--on-protection-overlay-modification`: expanding `/* $1 */\n$2$2` triggers the early-exit protection when the input for `$1` is autofilled, but adding a newline `/* $1\n */\n$2$2` somehow avoids it, and then throws an out of bounds error instead.
> Test and fix problem with mirror+autofill interaction

- yasnippet.el
fixes #561. I will delay merging this until after the release since I changed around the implementation of `yas-next-field` (in a potentially breaking way). EDIT: indeed the tests are indicating breakage.
> add yas-next-field-will-exit-p

- doc/snippet-expansion.org
- yasnippet.el
This PR collects a few fixes/improvements to the `yas-wrap-around-region` feature.
- fixes #374.
- fixes #523.
- fixes #636.
> Fix some issues with yas-wrap-around-region

- yasnippet-tests.el
- yasnippet.el
fixes #679.
```
* yasnippet.el (yas--indent-region): Indent only non-empty lines.
* yasnippet-tests.el (basic-indentation): Add empy and non-empty (but
blank) lines in test snippet.
```
> Don't indent empty lines in snippet expansion

- doc/snippet-development.org
- yasnippet-tests.el
- yasnippet.el
fix #640.
```
* doc/snippet-development.org: New "Indentation markers" section.
* yasnippet-tests.el (indentation-markers): New test.
* yasnippet.el (yas--indent-markers): New variable.
(yas--indent): Use it instead of searching for $> directly.
(yas--indent-parse-create): New function, records occurences of $> into
`yas--indent-markers'.
(yas--snippet-parse-create): Call it.
```
> Document $> and fix escaping

- doc/snippet-development.org
- yasnippet.el
```
yas-find-snippets was removed by [1].
* doc/snippet-development.org: Add keybindings on same line as command
names, fixup intra document links, and remove mention of non-existent
command yas-find-snippets.
* yasnippet.el (yas-load-snippet-buffer):
(yas-load-snippet-buffer-and-close): Fix docstring formatting.
[1]: "cleanup: remove `yas/find-snippets\', complicated and no one seems
to use it anyway" 29 May, 2012 433c93746534ebb062afe4dbc7690f736be72d42.
```
> Fix outdated and misformatted docs

- yasnippet.el
fixes #381, replace close #594.
```
* yasnippet.el (yas--apply-transform): Don't let-bind yas-moving-away-p
to nil, it's nil by default.
(yas-next-field): Call `yas--field-update-display' instead of only
calling `yas--eval-lisp' so that the result of the transform is inserted
into the buffer.
```
> Fix field transform application in yas-next-field

- yasnippet.el
fixes #687.
```
during snippet creation.  The snippet creation manipulates the
syntax-table which can lead to conflicts (see also
http://debbugs.gnu.org/cgi/bugreport.cgi?bug=23443).
* yasnippet.el (yas-expand-snippet): Let-bind syntax-propertize-function
to nil and then call syntax-ppss-flush-cache afterwards.
```
> Don't use major-mode syntax-propertize-function

- yasnippet.el
```
* yasnippet.el (yas--save-backquotes): Parse all backquoted lisp forms
and only then evaluate them.
```
cf #141, but generalizing to multiple expressions
> Problem lies in yas/replace-backquotes function.
It starts with snippet content inserted into buffer. It evaluates as follows:
- parse lisp code
- evaluate lisp code
- remove snippet lisp code from buffer
> It will work if order would be:
- parse lisp code
- remove snippet lisp code from buffer
- evaluate lisp code
> Separate parsing from evaluation of backquote lisp

- yasnippet.el
Fixes #720.
```
Since modification hooks run just after any function that changes buffer
contents, it's important to save the match data, or else the code doing
the modification can become really confused.  See also Emacs bugs #23917
and #23869.
* yasnippet.el (yas--on-field-overlay-modification): Wrap main body in
`save-match-data'.
```
> Don't clobber match data in modification hooks

- yasnippet.el
Slight tweak of code mentioned at https://github.com/joaotavora/yasnippet/pull/694#issuecomment-220967384, I don't want to lose the default file name in `C-c C-c`.
Close #694.
> Simplify `yas-new-snippet' load&save logic

- yasnippet-tests.el
- yasnippet.el
Fixes #733.
```
`buffer-file-name' is a permanent buffer-local variable, so if we reuse
the "*new snippet*" buffer, we could end up visiting the last new
snippet's file.
* yasnippet.el (yas-load-snippet-buffer-and-close): Rename the "*new
snippet*" buffer when making it visit a file.
```
> Fix saving of new snippets

- CONTRIBUTING.md
- NEWS
- README.mdown
- doc/index.org
- doc/nav-menu.html.inc
- yasnippet.el
Since the new repo destination is now under **joaotavora**, I've fixed all
the stale links to point to the new destination
Also, see this PR: https://github.com/melpa/melpa/pull/4301
Close #704.
> Replaced all occurances of `capitaomorte'

- yasnippet.el
Except this littte improvement I propose to use 'lazy-loading' and 'eager-loading' instead of 'just-in-time' and 'immediate/<unspecified>'. If you agree I create another PR for this.
> Improve final message produced by yas-reload-all

- yasnippet-tests.el
- yasnippet.el
Refer: https://github.com/joaotavora/yasnippet/issues/561#issuecomment-233258767
```
* yasnippet.el (yas-active-snippets): Rename from
yas--snippets-at-point, adjust callers.  Handle arbitrary positions and
ranges as a parameter.
```
> Promote yas--snippets-at-point to a public API (yas-active-snippets)

- yasnippet.el
```
* yasnippet.el (yas--mirror-update-display): Check yas-indent-line
before indenting.
```
Fixes #739. ~~but this doesn't help if only the snippet binds `yas-indent-line`, because the snippet's `expand-env` is only in effect during the initial expansion. Have to think about whether/how to apply it later.~~ This might affect #702 implementation too.
> Respect yas-indent-line for mirror updates

- doc/faq.org
- doc/snippet-expansion.org
- yasnippet-tests.el
- yasnippet.el
Fixes #289.
Fixes #708.
Fixes #761.
Close #763.
Fixes #649.
TODO:
> Use :filter instead of yas--fallback, and support org-src-tab-acts-natively

- yasnippet-tests.el
- yasnippet.el
Fixes #768.
```
* yasnippet.el (yas--update-mirrors): Delay indentation until all
mirrors are updated.
(yas--mirror-update-display): Don't indent here.
* yasnippet-tests.el (single-line-multi-mirror-indentation-2): New test.
```
> Fix whitespace lossage between mirrors

- yasnippet-tests.el
- yasnippet.el
Close #28.
The example there would be
``` elisp
(defun yas-delete (regexp)
(goto-char yas-snippet-beg)
(while (re-search-forward regexp yas-snippet-end t)
(replace-match "")))
```
```
#name : mock
#key : mock
#expand-env: ((yas-after-exit-snippet-hook (lambda () (yas-delete "\\.[a-zA-Z0-9]+(IGNORE)"))))
${1:mock} = mock()
$1.expects(:${2:method}).with(${3:IGNORE}).returns(${4:IGNORE}).times(${5:IGNORE})
```
> Snippet local exit hooks

- doc/snippet-expansion.org
- yasnippet.el
See https://github.com/joaotavora/yasnippet/pull/638#issue-121831941:
> the condition was effectively ignored for a long time due to only checking `yas-expand-from-trigger-key` and not `yas-expand`, I wonder if people will start complaining that snippets no longer work in comments...
It did happen, so I'm changing the default to `t`.
Close #765.
Close #773.
Close #772.
Also #706.
```
* yasnippet.el (yas-buffer-local-condition): Change default to t.
* doc/snippet-expansion.org: Update documentation.
```
> Let snippets expand in strings/comments by default

- yasnippet-tests.el
- yasnippet.el
This is #779 squashed and tweaked a bit.
Replace/ close #779.
Fix #780.
```
* yasnippet.el (yas--eval-for-effect): Use `yas--safely-call-fun'
instead of `yas--safely-run-hook'.
(yas--safely-call-fun): Display the called argument (even a lambda) on
errors.
(yas--safely-run-hook): Take a hook variable instead of the hook value
itself.  Use `run-hooks' to take buffer-local values into account.
This means it’s no longer possible to warn which hook function had an
error.
(yas--check-commit-snippet): Refactor to conform to
`yas--safely-run-hooks'.
* yasnippet-tests.el (snippet-exit-hooks-bindings): New test that
checks for buffer-local, global and env hooks support.
```
> Fix running hook variable set as buffer-local (v2)

- yasnippet-tests.el
- yasnippet.el
* yasnippet.el (yas-expand-snippet): Use the snippet lexical binding
when moving field. This prevents getting an error when calling a
function variable defined in expand-env.
* yasnippet-tests.el (snippet-mirror-bindings): Add a test to check if
we can call a function variable defined in the snippet environment.
Note: I also saw there could be a bug (not related to that patch). If the mirror transformation doesn't contain any character before (at indentation), blank spaces after the mirror will be removed. This is because the mirror transformation may return `""`.
> Fix mirror transformation error with expand-env

- yasnippet-tests.el
- yasnippet.el
Fix #269.
```
* yasnippet.el (yas--place-overlays): Don't move active field overlays
unless we're working on the innermost snippet.
(yas--move-to-field): Keep `yas--active-field-overlay's `yas--snippet'
property in sync with its `yas--field' property.
* yasnippet-tests.el (nested-snippet-expansion-1): Rename from
nested-snippet-expansion-1.
(nested-snippet-expansion-2, nested-snippet-expansion-3): New tests.
```
> Fix nested snippet expansion

- yasnippet.el
1st commit fixes #756.
2nd is for #782. It doesn't fix it by itself, that requires rust-lang/rust-mode#197 as well.
> Don't disable modification hooks; don't disable syntax-propertize-function as much

- yasnippet-tests.el
- yasnippet.el
Fixes #794.
```
* yasnippet-tests.el (auto-fill-with-multiparagraph): New test.
* yasnippet.el (yas--auto-fill): Don't snapshot markers outside of
current paragraph.
(yas--goto-saved-location, yas--snapshot-marker-location): Count
newlines as whitespace (even if mode marks them as non-whitespace
syntax, e.g., comment end).
(yas--snapshot-overlay-location, yas--restore-overlay-location): Don't
snapshot overlay position which is outside of BEG .. END.
```
> Fix problems with auto-fill-mode interaction

- yasnippet.el
Fixes #653.
```
* yasnippet.el (yas-expand-snippet): Unset `deactivate-mark'.
```
> Fix ${0:soon-to-be-deleted} with no other fields

- yasnippet.el
Fixes #806.
```
* yasnippet.el (yas--maybe-expand-key-filter):
(yas--maybe-expand-from-keymap-filter): Let-bind
`yas--condition-cache-timestamp' to the current time.
```
> Fix condition timestamps in key filter functions

- yasnippet.el
Should mostly solve #478.
```
* yasnippet.el (yas--commit-snippet): Remove overlay object after
deleting it.
(yas--markers-to-points): Drop marker object.
(yas--points-to-markers): Create a new marker object.
```
> Don't leave unreadable objects in the undo list

- yasnippet.el
```
* yasnippet.el (yas--indent-parse-create): Let-bind
`parse-sexp-lookup-properties' to nil.
```
Fixes #815.
> Fix field parsing in modes that use the `syntax-table' property

- yasnippet.el
Fixes #814.
```
* yasnippet.el (yas--on-field-overlay-modification): Don't commit
snippet again if the the triggering overlay has already been deleted.
```
> Don't delete snippets more than once.

- yasnippet-tests.el
- yasnippet.el
Fixes problem created by #822, noted in by @longitude in https://github.com/joaotavora/yasnippet/issues/821#issuecomment-306224541
```
* yasnippet.el (yas--get-indent-undo-pos): Renamed from
yas--return-first-indent-undo.
(yas-expand-snippet): Bind it to line beginning of snippet expansion
position.
* yasnippet-tests.el (undo-indentation, undo-indentation-multiline):
New tests for this and previous fix.
```
> Fix undo information recording for multiline snippets

- yasnippet.el
Resolves #828.
```
* yasnippet.el (yas-overlay-priority): New custom option.
(yas--make-control-overlay, yas--make-move-active-field-overlay): Use
it.
```
> Allow customizing overlay priority

- Rakefile
- yasnippet-debug.el
- yasnippet.el
`yasnippet-debug.el` can now be used to quickly test and debug a snippet
in a file.
> Debugging improvements

- yasnippet.el
Avoid `yas--auto-fill` call `yas--update-mirrors` without setting the snippet environment.
When an snippet like the one bellow is expanded and that auto-fill-mode is activated, the snippet is re-indented when you press space in a field replacement.
```snippet
-------------------------------------------------------------------------------
-- NAME    : ${1:function_name}
-- CREATED : `(capitalize (format-time-string "%d/%m/%Y"))`
-- AUTHOR  : `(and (boundp 'user-ngram) user-ngram)`
-------------------------------------------------------------------------------
-- ARGS  :
-- - $3
-------------------------------------------------------------------------------
-- RETURN  : ${4:True when all is OK, false in any other cases'}
----------------------------------------------------------------------- …
```
> Avoid to indent snippets having setup `(yas-indent-line 'fixed)`

- .travis.yml
- Rakefile
- yasnippet-debug.el
- yasnippet-tests.el
- yasnippet.el
I'll probably need to release 0.12.1 with this soon, since users are going to see a bunch of (actually harmless) compile errors when installing.
> Fix compilation warnings, add compile_all to standard test

- yasnippet.el
Fixes #840.
```
* yasnippet.el (yas-expand-snippet): Only keep region active if we are
going to field $0 and it has some text.
```
> Don't keep region active when expanding from keymap

- yasnippet-tests.el
- yasnippet.el
Fixes #850.
```
* yasnippet.el (yas-also-auto-indent-first-line): New option.
(yas--indent-region): Also indent empty lines if it's set.
* yasnippet-tests.el (yas-also-indent-empty-lines): New test.
```
> Add yas-also-indent-empty-lines to allow old indent behavior

- NEWS
- yasnippet.el
This release just includes the fix for the regression in #840. Other outstanding fixes are too risky for a micro release, they will have to wait for 0.13.
```
* NEWS: Add changes for 0.12.2.
* yasnippet.el: Bump version.
* snippets: Update submodule.
```
> Release 0.12.2

- yasnippet-tests.el
- yasnippet.el
Fixes #842.
```
* yasnippet.el (yas-new-snippet-buffer-name): New constant, holds the
name of new snippet buffers.  Change it to "+new-snippet+" to avoid
the leading "*" from fooling whitespace-global-mode into thinking it
shouldn't activate.
(yas-new-snippet):
* yasnippet-tests.el (snippet-save): Use the constant instead of
hardcoding the literal string.
```
> Let whitespace-global-mode work in new snippet buffers

- yasnippet.el
Fixes #862.
```
* yasnippet.el (yas--parse-template): Allow trailing space after "#
--" marker.
```
> Allow "# --" end-of-header marker to have trailing space

- yasnippet-tests.el
- yasnippet.el
Fixes #883.
```
* yasnippet.el (yas-expand-snippet): Only use the `to-delete' text if
`region-active-p' return true.
* yasnippet-tests.el (expand-with-unused-yas-selected-text): New test.
```
> Don't set yas-selected-text to non-selected text

- yasnippet.el
> * yasnippet.el (yas-key-syntaxes): Prefer the longest key.

- yasnippet-tests.el
- yasnippet.el
Problem reported at https://emacs.stackexchange.com/questions/38242/problem-redoing-with-yasnippet.
```
On 2018-01-01 "Fix undo when first line indentation moves snippet
forward", `yas--take-care-of-redo' removed the BEG and END arguments,
but the call added to `buffer-undo-list' from `yas--snippet-revive',
was not updated accordingly.
* yasnippet.el (yas--snippet-revive): Remove `beg' and `end' from
`yas--take-care-of-redo' entry.
* yasnippet-tests.el (undo-redo): New test.
```
> Update `yas--take-care-of-redo' call in buffer undo list

- yasnippet-debug.el
- yasnippet-tests.el
- yasnippet.el
Resolves #753.
```
* yasnippet.el (yasnippet-unload-function): New function.
* yasnippet-debug.el (yas-exterminate-package): Remove, it was only
doing a partial job of undoing modes, and uninterning is entirely not
needed.
```
> Add yasnippet-unload-function

- yasnippet-tests.el
- yasnippet.el
Resolves #408.
```
Rather than embedding the conditionality inside the function body, and
hardcoding fallback to `delete-char'.  This allows users who want, for
example, to use backspace for field skipping to simply do
(define-key yas-minor-mode-map (kbd "DEL")
yas-maybe-skip-and-clear-field)
* yasnippet.el (yas-skip-and-clear-field, yas-current-field)
(yas--maybe-clear-field-filter): New command and function, extracted
from yas-skip-and-clear-or-delete-char.
(yas-skip-and-clear-or-delete-char): Mark obsolete.
(yas-maybe-skip-and-clear-field): New constant, for conditional
binding.
(yas-keymap): Bind it to `C-d' instead of
`yas-skip-and-clear-or-delete-char'.
* yasnippet-tests.el (delete-numberless-inner-snippet-issue-562): Use
`yas-skip-and-clear-field' instead of …
```
> Bind field skip and clear command conditionally

- doc/snippet-development.org
* doc/snippet-development.org: Fix typos.
> Fix typos in "Writing Templates" documentation

- yasnippet-tests.el
- yasnippet.el
Fix #800.
```
* yasnippet.el (yas--backquote-markers-and-strings): Remove.
(yas--save-backquotes): Return list of backquote expressions.
(yas--restore-backquotes): Receive it as a parameter.
(yas--snippet-parse-create): Keep it in a local variable.
* yasnippet-tests.el (yas-no-memory-of-bad-snippet): New test.
```
> Don't use global variable for backquote expression locations

- yasnippet-tests.el
- yasnippet.el
Fixes #899.
```
The previous changed failed to account for command snippets which have
lists for bodies, not strings.
* yasnippet.el (yas-expand-snippet): Don't error if SNIPPET is a list
representing a command snippet body.
* yasnippet-tests.el (yas-expand-command-snippet): New test.
```
> Fix expansion of commands snippet

- yasnippet.el
Fixes #901.
```
* yasnippet.el (yas-snippet-mode-buffer-p): Instead of a string
comparison of file names to check whether the buffer file is in on of
the `yas-snippet-dirs', use the builtin file-in-directory-p function.
```
> Make yas-snippet-mode-buffer-p robust against symlinks

- yasnippet.el
Fix #906.
```
* yasnippet.el (yas--indent): When `yas-indent-line' is `fixed',
instead of calling `indent-to-column' on each line directly, bind
`indent-line-function' and use `yas--indent-region'.  The latter uses
some clever tricks to keep field regions from extending into the newly
created whitespace.
```
> Use fancy field adjustment for fixed indent too

- yasnippet-tests.el
- yasnippet.el
Fixes #912.
```
Unless yas-also-auto-indent-first-line applies.
* yasnippet.el (yas--indent): Check that forward-line successfully
moved 1 line forward before trying to indent.
* yasnippet-tests.el (yas-indent-first-line)
(yas-indent-first-line-fixed): New tests.
```
> Don't indent first and only line of expanded snippet

- yasnippet.el
Continuation of #920, turns out I made the watcher too eager.
```
* yasnippet.el (yas--watch-auto-fill): If we're called from
kill-all-local-variables, we don't need to check this, because
auto-fill-function will shortly be set to nil as well.
```
> ; Don't enter debugger for kill-all-local-variables case

- README.mdown
- doc/faq.org
In the README and in the FAQ, mention and link to the list of support
issues in the Github issue tracker.
Rewrite README.mdown slightly for readability and suggest the GH
tracker as primary place for YASnippet discussion.
Retire the YASnippet google group.
* README.mdown (Manual, issues, etc): Mention docs, support issues
and issue tracker separately. Remove reference to the YASnippet
google group.
(Where are the snippets?): Properly write YASnippet for
consistence.
* doc/faq.org: Add note and link to support issues.
> Tweak bug-reporting information slightly

- doc/snippet-development.org
- yasnippet-tests.el
- yasnippet.el
* yasnippet-tests.el (auto-next-field): New test.
(yas-saving-variables): Move up in the file.
* yasnippet.el (yas--auto-next): New helper.
(yas-auto-next): New user-visible snippet helper.
* doc/snippet-development.org (Choosing fields value from a list
and other tricks): Add mention of yas-auto-next.
> Close #937: Officially support automatically moving to next field

- yasnippet.el
I doubt yasnippet even works on Emacs 22 anyway. The automated tests only go back to 23.4, and I can't even build earlier than 24.3 locally.
```
* yasnippet.el (region-active-p, locate-dominating-stop-dir-regexp)
(locate-dominating-file): Remove.
```
> Remove compatibility code for Emacs 22 and earlier

- yasnippet-tests.el
- yasnippet.el
Fixes #953.
```
Suggested by OGAWA Hirofumi in
https://github.com/joaotavora/yasnippet/issues/953.
* yasnippet.el (yas--snippet-create): Call before and after change
functions around yas--snippet-parse-create.
* yasnippet-tests.el (indent-cc-mode-2): New test.
```
> Fix another failure of cc-mode indentation

- yasnippet-debug.el
- yasnippet-tests.el
- yasnippet.el
Fix #959 (?)
```
* yasnippet.el (yas--on-field-overlay-modification): Call
yas--advance-end-maybe on all pending active snippets in case of
stacked expansion.
```
> Handle field adjust of pending active fields

- doc/snippet-expansion.org
- yasnippet-tests.el
- yasnippet.el
See https://github.com/joaotavora/yasnippet/issues/936#issuecomment-388187042 and followups.
```
* yasnippet.el (yas--modes-to-activate): If a mode doesn't have a
`derived-mode-parent' property, use `fundamental-mode'.
* yasnippet-tests.el (loading-with-cyclic-parenthood)
(issue-492-and-494): Expect fundamental-mode to be active.
* doc/snippet-expansion.org (Eligible snippets): Mention that
fundamental-mode is a fallback parent mode.
```
> Consider fundamental-mode as ultimate ancestor

- doc/snippet-development.org
- yasnippet.el
Close #934.
```
* yasnippet.el (yas-completing-read): New function.
(yas-verify-value): Simplify with `member' instead of `cl-notany'.
* doc/snippet-development.org (Template Syntax): Show
`yas-completing-read' instead of `yas-choose-value' in the example.
```
> Add yas-completing-read

- yasnippet.el
Close #943.
```
* yasnippet.el (yas-maybe-expand-abbrev-key-filter): Renamed from
yas--maybe-expand-key-filter.
```
> New public function yas-maybe-expand-abbrev-key-filter

- yasnippet.el
Might fix #964.
```
* yasnippet.el (yas--snippet-create): Let-bind
inhibit-modification-hooks for snippet insertion, so that we don't
call change functions automatically, we already call them manually
after insertion and parsing.
```
> Don't call before/after change-functions twice

- yasnippet.el
Fixes #973, close #978.
```
Since we now check conditions in conditional keybindings, it can be
evaluated before 'this-command' has been assigned.
* yasnippet.el (yas-not-string-or-comment-condition): Remove check of
'this-command'.
```
> Don't check this-command in yas-not-string-or-comment-condition

- doc/faq.org
- yasnippet.el
Fixes #987.
```
* yasnippet.el (yas-keymap-disable-hook): New hook.
(yas-filtered-definition): New function.
(yas-keymap): Use it.
```
> Allow disabling snippet keybindings from hook

- yasnippet.el
Close #982
```
* yasnippet.el (yas-inhibit-overlay-modification-protection): New
variable.
(yas--on-protection-overlay-modification): Consult it.
```
> Make overlay-modification protection optional

- yasnippet-tests.el
- yasnippet.el
Fixes #995.
```
* yasnippet.el (yas--todo-snippet-indent): New variable.
(yas--on-field-overlay-modification): Save snippet to it, and don't
indent after mirror update.
(yas--do-todo-field-updates): New function.
(yas--post-command-handler): Call it.
(yas--snippet-field-mirrors, yas--indent-mirrors-of-snippet): New
functions, split out from...
(yas--snippet-field-mirrors): ...here.
* yasnippet-tests.el (yas-test-delete-and-insert-command)
(indent-mirrors-on-complex-update): New test and helper function.
```
> Do auto indentation only in post command hook

- yasnippet-tests.el
- yasnippet.el
Fixes #996
```
For deletion, we need to check the bounds before the deletion happens,
otherwise the overlay may already be moved to wrong place.
* yasnippet.el (yas--before-change-modified-snippets): New variable.
(yas--gather-active-snippets): New function.
(yas--on-field-overlay-modification): Use it.
```
> Fix field adjustment on deletion

- doc/faq.org
I got an error when trying to define a keyboard shortcut for yas-prev,
as given in the FAQ. It appears that the correct function definition is
yas-prev-field.
Thank you for this really fantastic package!
> Fix FAQ: yas-prev should be yas-prev-field

- yasnippet-debug.el
- yasnippet-tests.el
- yasnippet.el
Fixes #1006.
```
* yasnippet.el (yas--snippet-revive): Add revived snippet to
yas--active-snippets.
* yasnippet-debug.el (yas-debug-snippets): Print yas--active-snippets
length.
```
> Fix snippet undo

- yasnippet-tests.el
- yasnippet.el
Fixes #1010.
```
* yasnippet.el (yas--auto-next): Loop again after moving to the next
field.
```
> Handle multiple uses of yas-auto-next

- yasnippet.el
When I use yas-new-snippet to create a new snippet, when the scrippet is
with a complex name (such as "test.snippet"), after I save the snippet,
I can't use yas-insert-snippet to insert it. I do can see it in the menu
bar, though.
This patch fixes this problem.
> Fix can't insert a new snippet.

- NEWS
- yasnippet.el
[1]: https://git.savannah.gnu.org/cgit/emacs/elpa.git/commit/?id=a018267721a477822ea6715770a1bf05f60c3e3a
> Release 0.14.0

- yasnippet-tests.el
- yasnippet.el
Fixes #1038
```
* yasnippet.el (yas--advance-end-maybe-previous-fields): New function.
(yas--commit-snippet, yas--on-field-overlay-modification)
(yas-expand-snippet): Use it, so that all active fields will be
extended properly, even in case of deeply nested snippet expansion.
* yasnippet-tests.el (nested-snippet-expansion-depth-2): New test.
```
> Fix failure on depth 2+ nested snippets

- yasnippet-tests.el
- yasnippet.el
Fixes joaotavora/eglot#336.  I think the other calls to
`yas--scan-sexps` may need to be replaced as well.
```
* yasnippet.el (yas--scan-for-field-end): New function.
(yas--field-parse-create): Use it instead of yas--scan-sexps, which
isn't able to distinguish between ${...} (a nested field) and
{...} (plain old braces in the snippet text).
* yasnippet-tests.el (yas-escaping-close-brace): New test.
```
> Scan nested fields properly

- yasnippet.el
Maybe fixes #1041.
```
* yasnippet.el (yas--snippet-create): Bind before-change-functions and
after-change-functions to nil instead of inhibit-modification-hooks to
t while expanding snippet.  The latter also needlessly blocks overlay
and text property modification hooks (which we don't call ourselves
afterwards).  This way we allow packages like iedit to better
co-operate with yasnippet.
```
> Don't bind inhibit-modification-hooks in yas--snippet-create

- yasnippet-tests.el
- yasnippet.el
Fixes problem that came up in #1055.
```
* yasnippet.el (yas--eval-for-string): Convert error to a string,
rather than returning the error data (which can only lead to confusing
type errors later when code expecting a string gets a list).
* yasnippet-tests.el (yas-no-memory-of-bad-snippet): Adjust test, now
that snippet expansion swallows errors properly.
```
> Handle errors during evaluation properly

- yasnippet-tests.el
yas-reload-all does not undo the memoization done in yas--all-parents, which causes the issue-492-and-494 test to fail when run after any tests that expands yas-with-some-interesting-snippet-dirs.
With the memoization enabled, c++-mode is considered a parent of c-mode, causing the issue-492-and-494 test to fail.  With the memoization reset, this does not occur.
> Undo all-parents memoization in test

- yasnippet.el
Before this commit,
(yas--all-parents 'lisp-mode) would return:
`(lisp-mode lisp-data-mode prog-mode fundamental-mode fundamental-mode)`
which would cause duplicated entries when prompting (if the snippet were for fundamental-mode).
> (yas--all-parents): delete-dups for fundamental-mode

- yasnippet.el
I've written a couple of yasnippets for ledger, that involve user input through org-read-date. Something like this:
```
`(format-time-string "%Y/%m/%d" (org-read-date nil t))` ${0:Charge to Credit Card}
${2:Exp}  ${1:\$100}
Lia:CreditCard
```
However, occasionally I change my mind after expanding the yasnippet, and hit C-g. This completely ruins undo-tree, it's basically unusable. 
The patch I've proposed fixes this, though IDK if there's a more elegant way to fix this. I noticed that if the block of code that modifies the buffer-undo-list still executes after hitting C-g, everything is fine. So, I'm wrapping the whole block that is "inserting" the snippet with an unwind-protect, to ensure that the proper values still get pushed to buffer-undo-list. 
Is this good?
> Push modifications to buffer-undo-list, even if unwinding
