joaotavora/yasnippet

.travis.yml, Rakefile
```
* .travis.yml: get Emacs from https://github.com/npostavs/emacs-travis/releases
```
=> Experimenting with Emacs install for Travis CI

yasnippet.el
closes #682.
```
Make sure output that occurs in normal use goes to verbosity levels 3 or
higher, and level 2 and below are reserved for something unexpected
happening.  Level 3 (the new default) should be a reasonably quiet but
informative level.
* yasnippet.el (yas--read-keybinding), yas--safely-run-hooks):
(yas--on-protection-overlay-modification):
(yas--indent-according-to-mode): Put warnings at verbosity level 2.
(yas--load-yas-setup-file, yas-load-directory):
(yas--load-directory-1, yas--load-snippet-dirs):
(yas-expand-snippet, yas--load-pending-jits): Put per-file loading and
other debug messages at level 4.
(yas-load-snippet-buffer, yas--template-get-file, yas-reload-all): Put
top level loading messages at level 3 (or 2 if there were errors).
(yas--define-menu-1, …
```
=> Make yasnippet less chatty

yasnippet.el
replace/ close #625.
rebase of/ close #309.
```
* yasnippet.el (yas-new-snippet-default): Add yas-selected-text.
(yas-new-snippet): Let-bind yas-selected-text to region content.
Copyright-paperwork-exempt: yes
```
=> Add region contents to new snippet

yasnippet.el
```
These symbols were overlooked in backporting because they're not bound
or fbound.
* yasnippet.el (yas--define-menu-1): Rewrite with `cl-loop', and support
yas/ prefixed symbols.
```
Fixes #723.
=> Support yas/ symbols in yas-define-menu

NEWS, yasnippet.el
=> Release 0.11.0

yasnippet-tests.el, yasnippet.el
Fixes #579.
Fixes #362. Close #541.
Fixes #398.
~~I should add some tests for those, but this appears to be working.~~
Tests added.
```
* yasnippet.el (yas--snapshot-marker-location): New function, save a
regexp and whitespace count determining a marker's location in a line.
(yas--restore-marker-location): New function, restores a marker's
location based on info from `yas--snapshot-marker-location'.
(yas--indent-region): Use them to fix marker locations after indentation.
* yasnippet-tests.el (indent-org-property, indent-cc-mode):
(indent-snippet-mode): New tests.
```
=> Update handling of markers during indentation

doc/faq.org
A patch from @barak that never got forwarded upstream for some reason.
=> Typos and grammar

yasnippet-tests.el, yasnippet.el
```
* yasnippet-tests.el (yas-with-even-more-interesting-snippet-dirs): Add
debug declaration.
(yas--collect-menu-items): New function.
(test-yas-define-menu): Use it to become keymap format agnostic.
* yasnippet.el (yas--delete-from-keymap): This function deletes entries
created by `yas--update-template-menu', which are always list elements.
Skip other types of keymap elements.
(yas--define-menu-1): Create a keymap with a vector element instead of a
list with gensym symbol binding list.
```
=> Use more compact format for snippet menus

yasnippet.el
Fixes #784.
```
Save and restore all snippet marker and overlays in the current
paragraph around auto-fill calls.  Extend the marker/overlay snapshot
and restore mechanisms to work in multiline regions.
...
```
=> Fix interaction with c auto-fill

yasnippet.el
Fixes example snippet in https://github.com/joaotavora/yasnippet/issues/818#issuecomment-301317609
```
* yasnippet.el (yas--snippet-parse-create): End binding of
syntax-propertize-function once snippet field parsing is finished.
```
=> Restore syntax-propertize-function before indenting mirrors

yasnippet.el
Fixes #821.
```
* yasnippet.el (yas--first-indent-undo)
(yas--return-first-indent-undo): New variables.
(yas-expand-snippet): Use them to collect the exact undo info from
indenting the first snippet line, rather than trying to reconstruct
it.
(yas--indent-region): Put undo info from indenting snippet's first
line into `yas--first-indent-undo' if `yas--return-first-indent-undo'
is non-nil.
```
=> Handle undo of snippet 1st line indent properly

NEWS, yasnippet-debug.el, yasnippet-tests.el, yasnippet.el
0.12.0 should be released soon. Beginning of May perhaps.
=> Release 0.12.0

yasnippet.el
Fixes #844.
```
* yasnippet.el (yas-expand-snippet): Since the actual insertion must
happen with modification hooks inhibited, we can't rely on that
mechanism to clear the field.  Call yas--skip-and-clear-field-p on the
active field.
```
=> Let snippet insertion trigger active field clearing

yasnippet-tests.el, yasnippet.el
Fixes #869.
```
Fix undo when first line indentation moves snippet forward
* yasnippet.el (yas--first-indent-undo, yas--get-indent-undo-pos):
Remove.
(yas-expand-snippet): Move undo-related code from here...
(yas--snippet-create): ... to here.  Collect undo information from
yas--indent in the normal, unsuppressed way.
(yas--indent-region): Don't collect undo information specially.
(yas--take-care-of-redo): Remove unused parameters.
* yasnippet-tests.el (undo-indentation-1): Rename from
undo-indentation.
(undo-indentation-2): New test.
(undo-indentation-multiline-1): Rename from
undo-indentation-multiline.
(undo-indentation-multiline-2): New test.
```
=> Fix undo+indentation

.gitmodules, README.mdown, yasnippet.el
Fixes #834, fixes #775, resolves #848.
```
* snippets:
* yasmate: Remove.
* README.mdown: Suggest yasnippet-snippets and yasmate as possible
things to download rather than submodules.
* yasnippet.el (yas--default-user-snippets-dir): Remove.
(yas-snippet-dirs): Remove `yas--default-user-snippets-dir' from
default value.
```
=> Remove submodules (snippet and yasmate)

yasnippet-tests.el, yasnippet.el
=> * yasnippet.el (snippet-mode): Derive from prog-mode.

yasnippet-debug.el, yasnippet-tests.el, yasnippet.el
Hi @npostavs ,
So I got bored and decided to pick up #824 and try to fix it. I did, the code is messy but no messier than it already was. Added a test. 
Also, in a separate commit, unbroke the old C-u C-t behaviour provided by yasnippet-debug (and was suprised by very nice and fancy colourful debug stuff).
Have a look when you find a moment.
=> Fix issue 824

yasnippet.el
=> * yasnippet.el (yas--guess-snippet-directories): Guess major mode first.

yasnippet-tests.el, yasnippet.el
Fixes #835. Unfortunately, this requires an incompatible change to `yas-lookup-snippet`. We could add a replacement function for it instead, but I suspect that would be more hassle than it's worth since 99% of uses would be of the form `(yas-expand-snippet (yas-lookup-snippet NAME))` which continues to work fine. Although if I get bug reports after merging this, I might change my mind...
```
This allows proper handling of a snippet's expand-env field when doing
(yas-expand-snippet (yas-lookup-snippet NAME))
* yasnippet.el (yas-expand-snippet): Return the yas--template struct
instead of snippet body.
(yas-expand-snippet): Let first argument be a yas--template struct.
* yasnippet-tests.el (snippet-lookup, snippet-load-uuid): Update tests
accordingly.
(yas-lookup-snippet-with-env): New test. …
```
=> Change yas-lookup-snippet to return a yas--template struct

yasnippet.el
Ref: #873 #919
Instead of asking users one by one to add code to their init, might as well opt-in by default. Plus, give a warning rather than interrupting their other code with an error.
```
* yasnippet.el (yas--watch-autofill): New variable watcher to catch
the problem.
(yas--auto-fill): If `yas--original-auto-fill-function' is nil, print
a warning with some info instead of signaling an error.
```
=> ; Try to get more info about #873/919

yasnippet.el
See [Emacs Bug#30931](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=30931).
```
Don't add to disabled undo list
Previously, we were unconditionally pushing entries onto the undo
list, which effectively enables undo, even in buffers where it's
disabled.
* yasnippet.el (yas--commit-snippet, yas--snippet-revive)
(yas--snippet-create): Check that `buffer-undo-list' is a list before
pushing to it.
```
```
Work around Emacs Bug#30931 (Misc_Free in undo list)
* yasnippet.el (yas--remove-misc-free-from-undo): New function.
(yas--save-restriction-and-widen): New macro.
(yas--eval-for-string, yas--snippet-parse-create)
(yas--indent-region, yas--save-backquotes)
(yas--restore-backquotes, yas--update-mirrors): Use it.
```
=> Work around Emacs Bug#30931 (Misc_Free in undo list)

yasnippet-tests.el
In response to a comment by @joaotavora on Issue #932.
=> Test for mirroring more than one field

yasnippet.el
=> * yasnippet.el (top-level): Call eldoc-add-command.

yasnippet-tests.el, yasnippet.el
Fixes #976.
```
There was some half-backed code getting confused between "plain"
snapshort info and line+snapshot info leading to some type errors when
expanding snippets in org-mode src blocks.  I had wrongly assumed the
failures were only due to org version 9 changes (in fact, the org
changes only affect snippet expansion for text-mode (and probably
other non-fontifying modes too)).  Reorganize the snapshotting
functions so that line+snaphot has the line info after the marker,
next to the rest of the snapshot info.  This removes the need for list
manipulation and simplifies the code.  Furthermore, let the
restoration functions take the info as a list, rather than separate
arguments, this removes the need for several uses of `apply'.
* yasnippet.el (yas--snapshot-location): Renamed from …
```
=> Fix obvious errors in org-mode hacks
